MotoGP/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MotoGP.Models;
using System.Diagnostics;

namespace MotoGP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Menu()
        {
            Random rnd = new Random();
            int numRand = rnd.Next(1, 5);
            ViewData["BannerNr."] = numRand;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MotoGP/Controllers/InfoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MotoGP.Data;
using MotoGP.Models;
using MotoGP.Models.ViewModel;

namespace MotoGP.Controllers
{
    public class InfoController : Controller
    {
        private readonly GPContext gpContext;
        public InfoController(GPContext gPContext) 
        {
            this.gpContext = gPContext;
        }
        public IActionResult ListRaces()
        {
            ViewData["BannerNr."] = 0;
            var races = gpContext.Races.OrderBy(x => x.Date).ToList();
            return View(races);
        }

        public IActionResult ListRiders()
        {
            ViewData["BannerNr."] = 1;
            var races = gpContext.Riders
                .Include(b => b.Country)
                .OrderBy(x => x.Number).ToList();
            return View(races);
        }

        public IActionResult BuildMap()
        {
            
            ViewData["BannerNr."] = 0;
            var races = gpContext.Races.ToList();
            return View(races);
        }

        public IActionResult SelectRace(int raceID = 0)
        {
            RaceDetailViewModel model = new RaceDetailViewModel();
            if (raceID != 0) 
            {
                model.SelectedRace = gpContext.Races.Where(a => a.RaceID == raceID).FirstOrDefault();
            }
            model.raceID = raceID;
            model.Races = new SelectList(gpContext.Races.ToList(), "RaceID", "Name");

            ViewData["BannerNr."] = 0;
            return View(model);
        }

        public IActionResult ShowRace(int id)
        {

            ViewData["BannerNr."] = 0;
            var race = gpContext.Races.Find(id);
            return View(race);
        }
    }
}

MotoGP/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MotoGP.Data;
using MotoGP.Models;
using MotoGP.Models.ViewModel;

namespace MotoGP.Controllers
{
    public class ShopController : Controller
    {
        private readonly GPContext gPContext;
        public ShopController(GPContext gPContext)
        {
            this.gPContext = gPContext;
        }

        public IActionResult OrderTicket()
        {
            ViewData["BannerNr."] = 3;
            var selectList = new SelectList(gPContext.Countries.ToList(), "CountryID", "Name");
            ViewData["SelectList"] = selectList;
            ViewData["RacesList"] = gPContext.Races.ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult OrderTicket([Bind("Name,Address,Email,Number,CountryID,RaceID")]Ticket ticket)
        {

            ticket.OrderDate = DateTime.Now;
            if (ModelState.IsValid)
            {
                gPContext.Tickets.Add(ticket);
                gPContext.SaveChanges();

                return RedirectToAction("ConfirmOrder", new {id = ticket.TicketID});
            }
            else
            {
                var selectList = new SelectList(gPContext.Countries.ToList(), "CountryID", "Name");
                ViewData["SelectList"] = selectList;
                return View(ticket);
            }
        }

        public IActionResult ConfirmOrder(int id)
        {
            ViewData["BannerNr."] = 3;
            var ticket = gPContext.Tickets
                .Where(a => a.TicketID == id)
                .Include(a => a.Country)
                .Include(a => a.Race)
                .FirstOrDefault();
            return View(ticket);
        }
    
        public IActionResult ListTickets(int raceID= 0)
        {
            ListTicketsViewModel model = new ListTicketsViewModel();
            if (raceID > 0)
            {
                model.Tickets = gPContext.Tickets
                    .Include(a => a.Country)
                    .Include(a => a.Race)
                    .Where(a => a.RaceID == raceID).ToList();
            }
            else
            {
                model.Tickets = gPContext.Tickets
                    .Include(a => a.Country)
                    .Include(a => a.Race)
                    .ToList();
            }
            model.raceID = raceID;
            model.Races = new SelectList(gPContext.Races.ToList(), "RaceID", "Name");
            ViewData["BannerNr."] = 3;
            return View(model);
        }
    }
}

MotoGP/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_NewLayout.cshtml";
    ViewData["Title"] = "Home Page";
}

<style>
    .centered {
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }
</style>


<div class="centered">
    <a asp-action="Menu">
        <img src="~/images/banners/logo.png" width="400"/>
    </a>
</div>

MotoGP/Views/Home/Menu.cshtml
@{
    Layout = "~/Views/Shared/_NewLayout.cshtml";
    ViewData["Title"] = "Menu";
}

<style>
    .centered {
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }
    .bottom{
        position: fixed;
        bottom: 5%;
        left: 5%;
    }
    .flexed{
        display: flex;
    }

</style>

<div class="centered">
    <div class="flexed">
        <div>
            <a asp-controller="Info" asp-action="ListRaces">
                <img src="~/images/banners/races.png" />
            </a>
        </div>
        <div>
            <a asp-controller="Info" asp-action="ListTeams">
                <img src="~/images/banners/teams.png" />
            </a>
        </div>
    </div>
    <div class="flexed">
        <div>
            <a asp-controller="Info" asp-action="ListRiders">
                <img src="~/images/banners/riders.png" />
            </a>
        </div>
        <div>
            <a asp-controller="Shop" asp-action="OrderTicket">
                <img src="~/images/banners/tickets.png" />
            </a>
        </div>
    </div>

</div>

<div class="bottom">
    <a asp-action="ListTickets" asp-controller="Shop">
        Admin Tickets
    </a>
</div>